apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretwatchers.secretwatcher.aly.com
spec:
  group: secretwatcher.aly.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretName:
                  type: string
          required:
            - spec
  scope: Namespaced
  names:
    plural: secretwatchers
    singular: secretwatcher
    kind: SecretWatcher
    shortNames:
      - sw
